name: Update README.md

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README.md
    steps:
    - uses: actions/checkout@v2
    - name: Run update script
      shell: bash
      run: bin/update_readme

    - name: Commit and push if changed
      run: |-
        git config --global user.email "spitlo@users.noreply.github.com"
        git config --global user.name "GitHub Action Bot"
        git diff --quiet README.md || git commit -m "Update README.md" README.md
        git push
